### ISSUE TITLE
Something went wrong creating [files] error

### ISSUE THREAD

**Issue by richardbonneau** [yeet-bix/create-react-component-vscode#10]
Hi, I'm very interested in using your extension. However, when I try to to create a component, I get three errors saying `something went wrong creating...` one for each file. Do you have any idea of why this is happening? thank you.

**Comment by yeet-bix** [comment]
Hey mate, everything is working on my side. So let's try and figure out what's wrong!

Could you please provide me:

1. VSCode version
2. Operating System
3. Have you configured any settings? If so what settings?
4. Steps to reproduce
5. Any output to the console

Cheers 😄

**Comment by yeet-bix** [comment]
Closing as no response
