### ISSUE TITLE
Can't set createReactComponent.fileExtension in V0.1.1

### ISSUE THREAD

**Issue by Aidenbuis** [yeet-bix/create-react-component-vscode#14]
Hi! 👋 

I really enjoy the extension, but I can't set the fileExtension in VSCode to 'withoutX'.
There is no setting for it in the default Settings.json, and when I add it in the custom Settings.json it doesn't change the extension of the created files (see the second screenshot, where the line is greyed out). It still generates the .jsx files. 

Would you know what the problem is? 

Kind regards and thank you for your OS work,

Aiden

<img width="984" alt="CleanShot 2020-07-06 at 16 19 52@2x" src="https://user-images.githubusercontent.com/9105359/86603637-89766180-bfa4-11ea-98aa-7286c8ead006.png">

![CleanShot 2020-07-06 at 16 22 51@2x](https://user-images.githubusercontent.com/9105359/86603923-fb4eab00-bfa4-11ea-8e6b-0b936fe2a5a2.png)

**Comment by yeet-bix** [comment]
Hi @Aidenbuis 👋 

Thanks for opening this issue. The `fileExtension` setting was added in https://github.com/yeet-bix/create-react-component-vscode/pull/13 which I never created a release for on the vscode marketplace (😬 )

I have just pushed the release so it should be live any second now! Could you see if you can update the extension and see the setting work?

**Comment by Aidenbuis** [comment]
Thank you Yeet, works like a charm!
