### ISSUE TITLE
[Feature Requeust] Simple mode

### ISSUE THREAD

**Issue by Stanzilla** [yeet-bix/create-react-component-vscode#27]
I'm not sure if you are still working on this, but a "simple" mode that only generates the component file itself would be nice

**Comment by yeet-bix** [comment]
I believe what you are asking for is already supported! 

<img width="999" alt="image" src="https://github.com/user-attachments/assets/0901ff8a-dc47-4eb8-a046-384fb112e823">

Try setting `createReactComponent.module = false`
